services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: forecast-service-backend
    ports: 
      - "8081:8081"
    networks:
      - forecast_service_network

networks:
  forecast_service_network:
    driver: bridge
    