services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: forecast-service-backend
    env_file:
      - backend/.env
    ports: 
      - "8084:8080"
    networks:
      - forecast_service_network

networks:
  forecast_service_network:
    driver: bridge
    