services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: data-pipeline-backend
    ports: 
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      timescale:
        condition: service_healthy
    networks:
      - data_pipeline_network
    restart: unless-stopped


  mosquitto:
    image: eclipse-mosquitto
    container_name: data-pipeline-mosquitto
    ports: 
      - "1883:1883"
        #- "9001:9001"
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./start-mosquitto.sh:/start-mosquitto.sh
    command: ["/bin/sh", "/start-mosquitto.sh"]
    networks:
      - data_pipeline_network
    restart: unless-stopped

  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    container_name: data-pipeline-mqtt-explorer
    ports:
      - "4005:4000"
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    depends_on:
      - mosquitto
    networks:
      - data_pipeline_network
    restart: unless-stopped
  
  timescale:
    image: timescale/timescaledb:latest-pg14
    container_name: data-pipeline-timescale
    environment:
      POSTGRES_USER: ${TS_USER}
      POSTGRES_PASSWORD: ${TS_PASSWORD}
      POSTGRES_DB: ${TS_DB}
    volumes:
      - timescale-data:/var/lib/postgresql/data
    networks:
      - data_pipeline_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost"]
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 10s

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8085:8081"
    environment:
      PGWEB_DATABASE_URL: postgres://${TS_USER}:${TS_PASSWORD}@timescale:5432/${TS_DB}?sslmode=disable
    depends_on:
      timescale:
        condition: service_healthy
    networks:
      - data_pipeline_network
    restart: unless-stopped
  
  migrate:
    image: migrate/migrate
    container_name: data-pipeline-migrate
    env_file:
      - .env
    volumes:
      - ./internal/database/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://${TS_USER}:${TS_PASSWORD}@timescale:5432/${TS_DB}?sslmode=disable", "up"]
    depends_on:
      timescale:
        condition: service_healthy
    networks:
      - data_pipeline_network

networks:
  data_pipeline_network:
    driver: bridge

volumes:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
  timescale-data:
