services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: data-pipeline-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - data_pipeline_network
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    container_name: data-pipeline-mosquitto
    ports: 
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./start-mosquitto.sh:/start-mosquitto.sh
    command: ["/bin/sh", "/start-mosquitto.sh"]
    networks:
      - data_pipeline_network
    restart: unless-stopped
  
  timescale:
    image: timescale/timescaledb:latest-pg14
    container_name: data-pipeline-timescale
    environment:
      POSTGRES_USER: ${TS_USER}
      POSTGRES_PASSWORD: ${TS_PASSWORD}
      POSTGRES_DB: ${TS_DB}
    volumes:
      - timescale-data:/var/lib/postgresql/data
    networks:
      - data_pipeline_network
    restart: unless-stopped  

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      PGWEB_DATABASE_URL: postgres://${TS_USER}:${TS_PASSWORD}@timescale:5432/${TS_DB}?sslmode=disable
    depends_on:
      - timescale
    networks:
      - data_pipeline_network
    restart: unless-stopped

networks:
  data_pipeline_network:
    driver: bridge

volumes:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
  timescale-data:
